package ai.chronon.flink.deser

import org.apache.avro.Schema

object MyAvroSchemas {
  lazy val paFraud: Schema = {
    new Schema.Parser().parse("""
    {
      "type": "record",
      "name": "MLPPaPreFraudTransactionEventV15",
      "namespace": "com.airwallex.data.pa",
      "doc": "{\"key\":\"attemptId\",\"timeField\":\"createdAt\"}",
      "fields": [
        {"name": "accountActiveDays", "type": ["null", "double"], "default": null},
        {"name": "merchantId", "type": ["null", "string"], "default": null},
        {"name": "amount", "type": ["null", "double"], "default": null},
        {"name": "amountUsd", "type": ["null", "double"], "default": null},
        {"name": "billAddress", "type": ["null", "string"], "default": null},
        {"name": "billCity", "type": ["null", "string"], "default": null},
        {"name": "billCountry", "type": ["null", "string"], "default": null},
        {"name": "billEmail", "type": ["null", "string"], "default": null},
        {"name": "billFirstName", "type": ["null", "string"], "default": null},
        {"name": "billLastName", "type": ["null", "string"], "default": null},
        {"name": "billName", "type": ["null", "string"], "default": null},
        {"name": "billingPhoneNumber", "type": ["null", "string"], "default": null},
        {"name": "billStreet", "type": ["null", "string"], "default": null},
        {"name": "cardBin", "type": ["null", "string"], "default": null},
        {"name": "cardCategory", "type": ["null", "string"], "default": null},
        {"name": "cardHolderName", "type": ["null", "string"], "default": null},
        {"name": "cardCountry", "type": ["null", "string"], "default": null},
        {"name": "cardOrg", "type": ["null", "string"], "default": null},
        {"name": "cardToken", "type": ["null", "string"], "default": null},
        {"name": "cardType", "type": ["null", "string"], "default": null},
        {"name": "cleRegisterDays", "type": ["null", "double"], "default": null},
        {"name": "createdAt", "type": ["null", "long"], "default": null},
        {"name": "customerEmail", "type": ["null", "string"], "default": null},
        {"name": "merchantCustomerId", "type": ["null", "string"], "default": null},
        {"name": "customerIp", "type": ["null", "string"], "default": null},
        {"name": "customerIpCity", "type": ["null", "string"], "default": null},
        {"name": "customerIpCountry", "type": ["null", "string"], "default": null},
        {"name": "customerIpLat", "type": ["null", "double"], "default": null},
        {"name": "customerIpLon", "type": ["null", "double"], "default": null},
        {"name": "customerPhoneNumber", "type": ["null", "string"], "default": null},
        {"name": "deviceId", "type": ["null", "string"], "default": null},
        {"name": "deviceIp", "type": ["null", "string"], "default": null},
        {"name": "distinctCityCount", "type": ["null", "double"], "default": null},
        {"name": "distinctCountryCount", "type": ["null", "double"], "default": null},
        {"name": "paymentIntentId", "type": ["null", "string"], "default": null},
        {"name": "coalesceDeviceIpCustomerIp", "type": ["null", "string"], "default": null},
        {"name": "coalesceDeviceIpUserIpCidr24", "type": ["null", "string"], "default": null},
        {"name": "cardCommercial", "type": ["null", "string"], "default": null},
        {"name": "isCardPersonal", "type": ["null", "int"], "default": null},
        {"name": "isCrossBorder", "type": ["null", "int"], "default": null},
        {"name": "isRiskyAmount", "type": ["null", "int"], "default": null},
        {"name": "legalEntityId", "type": ["null", "string"], "default": null},
        {"name": "legalEntityActiveDays", "type": ["null", "double"], "default": null},
        {"name": "merchantMcc", "type": ["null", "string"], "default": null},
        {"name": "orderId", "type": ["null", "string"], "default": null},
        {"name": "paCustomerId", "type": ["null", "string"], "default": null},
        {"name": "pageLanguageCountry", "type": ["null", "string"], "default": null},
        {"name": "pageLanguageCountryLat", "type": ["null", "double"], "default": null},
        {"name": "pageLanguageCountryLon", "type": ["null", "double"], "default": null},
        {"name": "shipAddress", "type": ["null", "string"], "default": null},
        {"name": "shipCity", "type": ["null", "string"], "default": null},
        {"name": "shipCountry", "type": ["null", "string"], "default": null},
        {"name": "shippingStreet", "type": ["null", "string"], "default": null},
        {"name": "coalesceDeviceIpUserIpCidr28", "type": ["null", "string"], "default": null},
        {"name": "panEntryMode", "type": ["null", "string"], "default": null},
        {"name": "cardHolderVerificationMethod", "type": ["null", "string"], "default": null},
        {"name": "isEntryModeFallback", "type": ["null", "int"], "default": null},
        {"name": "terminalId", "type": ["null", "string"], "default": null},
        {"name": "accountActiveDateToMilliSec", "type": ["null", "long"], "default": null},
        {"name": "coalescePaCustomerIdCustomerId", "type": ["null", "string"], "default": null},
        {"name": "isCardPresent", "type": ["null", "int"], "default": null},
        {"name": "paymentMethod", "type": ["null", "string"], "default": null},
        {"name": "paymentMethodCategory", "type": ["null", "string"], "default": null},
        {"name": "decisionFlow", "type": ["null", "string"], "default": null},
        {"name": "attemptId", "type": ["null", "string"], "default": null},
        {"name": "iamUserId", "type": ["null", "string"], "default": null},
        {"name": "testAccountFlag", "type": ["null", "boolean"], "default": null},
        {"name": "attemptAmtStr", "type": ["null", "string"], "default": null},
        {"name": "currency", "type": ["null", "string"], "default": null},
        {"name": "attemptIntegrationType", "type": ["null", "string"], "default": null},
        {"name": "isAttemptAmtUsd10To100", "type": ["null", "int"], "default": null},
        {"name": "cardExpDaysGap", "type": ["null", "double"], "default": null},
        {"name": "morCustomerId", "type": ["null", "string"], "default": null},
        {"name": "localHour", "type": ["null", "string"], "default": null},
        {"name": "isDeviceIpAnonymous", "type": ["null", "int"], "default": null},
        {"name": "isDeviceIpHostingProvider", "type": ["null", "int"], "default": null},
        {"name": "isCookieEnabled", "type": ["null", "int"], "default": null},
        {"name": "deviceType", "type": ["null", "string"], "default": null},
        {"name": "deviceBrowser", "type": ["null", "string"], "default": null},
        {"name": "isRecurringMit", "type": ["null", "int"], "default": null},
        {"name": "isRecurringSubsequentPayment", "type": ["null", "int"], "default": null},
        {"name": "email", "type": ["null", "string"], "default": null},
        {"name": "cleRegisterCountry", "type": ["null", "string"], "default": null},
        {"name": "cleRegisterActiveGapDays", "type": ["null", "double"], "default": null},
        {"name": "isCardholderShipSameName", "type": ["null", "int"], "default": null},
        {"name": "isBillShipSameFirstLastName", "type": ["null", "int"], "default": null},
        {"name": "timezoneDiff", "type": ["null", "int"], "default": null},
        {"name": "isBillCustomerSameEmail", "type": ["null", "int"], "default": null},
        {"name": "billCityLon", "type": ["null", "double"], "default": null},
        {"name": "billSubcontinent", "type": ["null", "string"], "default": null},
        {"name": "billContinent", "type": ["null", "string"], "default": null},
        {"name": "customerIpSubcontinent", "type": ["null", "string"], "default": null},
        {"name": "customerIpContinent", "type": ["null", "string"], "default": null},
        {"name": "shipSubcontinent", "type": ["null", "string"], "default": null},
        {"name": "issueSubcontinent", "type": ["null", "string"], "default": null},
        {"name": "issueContinent", "type": ["null", "string"], "default": null},
        {"name": "cleRegisterSubcontinent", "type": ["null", "string"], "default": null},
        {"name": "pageLanguageSubcontinent", "type": ["null", "string"], "default": null},
        {"name": "formattedCustomerPhone", "type": ["null", "string"], "default": null},
        {"name": "distinctCountryCntV2", "type": ["null", "double"], "default": null},
        {"name": "distinctCountryRate", "type": ["null", "double"], "default": null},
        {"name": "distinctCityCntV2", "type": ["null", "double"], "default": null},
        {"name": "distinctCityRate", "type": ["null", "double"], "default": null},
        {"name": "distinctSubcontinentCnt", "type": ["null", "double"], "default": null},
        {"name": "distinctContinentCnt", "type": ["null", "double"], "default": null},
        {"name": "distinctSubcontinentRate", "type": ["null", "double"], "default": null},
        {"name": "distinctContinentRate", "type": ["null", "double"], "default": null},
        {"name": "billIssueCountryDist", "type": ["null", "double"], "default": null},
        {"name": "shipIssueCountryDist", "type": ["null", "double"], "default": null},
        {"name": "issueIpCountryDist", "type": ["null", "double"], "default": null},
        {"name": "languageIpCountryDist", "type": ["null", "double"], "default": null},
        {"name": "issueDipCountryDist", "type": ["null", "double"], "default": null},
        {"name": "shipBillCityDist", "type": ["null", "double"], "default": null},
        {"name": "avgShipBillCityIpDist", "type": ["null", "double"], "default": null},
        {"name": "avgShipBillIpCountryDist", "type": ["null", "double"], "default": null},
        {"name": "maxShipBillIpCountryDist", "type": ["null", "double"], "default": null},
        {"name": "avgIssueShipBillIpCountryDist", "type": ["null", "double"], "default": null},
        {"name": "maxIssueShipBillIpCountryDist", "type": ["null", "double"], "default": null},
        {"name": "cardLevel", "type": ["null", "string"], "default": null},
        {"name": "phone", "type": ["null", "string"], "default": null},
        {"name": "billCityIpDist", "type": ["null", "double"], "default": null},
        {"name": "cardBrand", "type": ["null", "string"], "default": null},
        {"name": "physicalTerminalId", "type": ["null", "string"], "default": null},
        {"name": "shippingPostalCode", "type": ["null", "string"], "default": null},
        {"name": "billingPostalCode", "type": ["null", "string"], "default": null},
        {"name": "emailPrefix", "type": ["null", "string"], "default": null},
        {"name": "emailSuffix", "type": ["null", "string"], "default": null},
        {"name": "AFTRecipientAccount", "type": ["null", "string"], "default": null},
        {"name": "AFTRecipientPanToken", "type": ["null", "string"], "default": null},
        {"name": "AFTRecipientAddress", "type": ["null", "string"], "default": null},
        {"name": "AFTRecipientName", "type": ["null", "string"], "default": null},
        {"name": "AFTRecipientAddressCountry", "type": ["null", "string"], "default": null},
        {"name": "AFTRecipientAddressCity", "type": ["null", "string"], "default": null},
        {"name": "AFTRecipientAddressPostalCode", "type": ["null", "string"], "default": null},
        {"name": "AFTRecipientAddressState", "type": ["null", "string"], "default": null},
        {"name": "AFTRecipientAddressStreet", "type": ["null", "string"], "default": null},
        {"name": "AFTIsCrossBorder", "type": ["null", "int"], "default": null},
        {"name": "userIpCidr24", "type": ["null", "string"], "default": null},
        {"name": "deviceIpCidr24", "type": ["null", "string"], "default": null},
        {"name": "emailPrefixIsConsecutive3Consonant", "type": ["null", "int"], "default": null},
        {"name": "emailPrefixIsConsecutive2DigitOnly", "type": ["null", "int"], "default": null},
        {"name": "emailPrefixIsConsecutive3Digit", "type": ["null", "int"], "default": null},
        {"name": "emailPrefixIsSpecialChar", "type": ["null", "int"], "default": null},
        {"name": "emailPrefixIsLength16", "type": ["null", "int"], "default": null}
      ]
    }
    """)
  }
}
